# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_id', models.CharField(max_length=256)),
                ('order_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=5000)),
                ('status', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
